// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB465TQnPX7WY3IVUO5v1DWr0CGHEaNjB0',
    appId: '1:939991255385:web:cebbf112de3cb5c5c82448',
    messagingSenderId: '939991255385',
    projectId: 'dftl-6c1e7',
    authDomain: 'dftl-6c1e7.firebaseapp.com',
    storageBucket: 'dftl-6c1e7.appspot.com',
    measurementId: 'G-T1P1WL9VN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc4GzpghU1s0Hy9p3r2C8MJyuIC7ezIQM',
    appId: '1:939991255385:android:6d4d49cc7f161a93c82448',
    messagingSenderId: '939991255385',
    projectId: 'dftl-6c1e7',
    storageBucket: 'dftl-6c1e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEsWquOr_QCgLVcWn4FVlYQf5PP92XBy8',
    appId: '1:939991255385:ios:be528de763ee73afc82448',
    messagingSenderId: '939991255385',
    projectId: 'dftl-6c1e7',
    storageBucket: 'dftl-6c1e7.appspot.com',
    iosBundleId: 'com.example.dftlPlatform',
  );

}